apiVersion: apps/v1
kind: Deployment
metadata:
  name: LibraryManagement
  labels:
    app: LibraryManagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: LibraryManagement
  template:
    metadata:
      labels:
        app: LibraryManagement
    spec:
      containers:
        - name: LibraryManagement
          image: "username/LibraryManagement:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
